---
title: "Histograms"
output: html_document
---

```{r load_in_data}
rm(list = ls())
library(datasets)
library(ggplot2)

data(airquality)
```

```{r basic_plot}
ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram()
```

```{r frequency_plot}
ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..))

```

```{r adjust_binwidth}
ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5)

```

```{r changing_axis_labels_1}
ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5) +
    scale_x_continuous(name = "Mean ozone in parts per billion") +
    scale_y_continuous(name = "Count")
```

```{r changing_axis_labels_2}
ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion") +
    scale_y_continuous(name = "Count")
```

```{r changing_ticks}
ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion",
                              breaks = seq(0, 175, 25),
                              limits=c(0, 175)) +
    scale_y_continuous(name = "Count")
``` 

```{r adding_title}
ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion",
                              breaks = seq(0, 175, 25),
                              limits=c(0, 175)) +
    scale_y_continuous(name = "Count") +
    ggtitle("Frequency histogram of mean ozone")

```

```{r changing_fill_1}
barfill <- "white"
barlines <- "darkblue"

ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5,
                   colour = barlines, fill = barfill) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion",
                              breaks = seq(0, 175, 25),
                              limits=c(0, 175)) +
    scale_y_continuous(name = "Count") +
    ggtitle("Frequency histogram of mean ozone")
```

```{r changing_fill_2}
barfill <- "#4271AE"
barlines <- "#1F3552"

ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5,
                   colour = barlines, fill = barfill) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion",
                              breaks = seq(0, 175, 25),
                              limits=c(0, 175)) +
    scale_y_continuous(name = "Count") +
    ggtitle("Frequency histogram of mean ozone")
```

```{r themes_white}
barfill <- "#4271AE"
barlines <- "#1F3552"

ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5,
                   colour = barlines, fill = barfill) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion",
                              breaks = seq(0, 175, 25),
                              limits=c(0, 175)) +
    scale_y_continuous(name = "Count") +
    ggtitle("Frequency histogram of mean ozone") +
    theme_bw()
```

```{r theme_fivethirtyeight}
library(ggthemes)
library(extrafont)

ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion",
                              breaks = seq(0, 175, 25),
                              limits=c(0, 175)) +
    scale_y_continuous(name = "Count") +
    ggtitle("Frequency histogram of mean ozone") +
    scale_color_fivethirtyeight() + 
    theme_fivethirtyeight()
```

```{r importing_fonts}
library(ggthemes)
library(extrafont)

ggplot(airquality, aes(x = Ozone)) + 
    geom_histogram(aes(y = ..count..), binwidth = 5) +
    scale_x_continuous(name = "Mean ozone in\nparts per billion",
                              breaks = seq(0, 175, 25),
                              limits=c(0, 175)) +
    scale_y_continuous(name = "Count") +
    ggtitle("Frequency histogram of mean ozone") +
    scale_color_fivethirtyeight() + 
    theme_fivethirtyeight()
```

- Changing themes
- Adding lines (horizontal and vertical)
- Multiple histograms (same plot)
- Customising legend
- Multiple plots (panel)

