---
title: "Creating basic graphs in R"
output: html_document
---

This tutorial will demonstrate how to create graphs in ggplot2. It will demonstrate the variety of graphs you can make without further customisation.

## List of graphs:
* Scatterplot
* Weighted scatterplot
* Linear regression plot
* Lowess curve plot
* Line graph
* Area graph
* Bar graph
* Stacked bar graph
* Box plot
* Histogram
* Density plot
* Function curve

## Stacked bar graph

```{r, cache=TRUE}
library(ggplot2)

stackedchart.data <- read.csv("stackedchart.csv")
p10 <- ggplot() + geom_bar(aes(y = percentage, x = year, fill = product), data = stackedchart.data, stat="identity")
p10
```

```{r, cache=TRUE}
p10 <- p10 + geom_text(data=stackedchart.data, aes(x = year, y = percentage, label = paste0(percentage,"%")))
p10
```

```{r, cache=TRUE}
library(plyr)
stackedchart.data <- as.data.frame(stackedchart.data)
stackedchart.data$product <- factor(stackedchart.data$product, levels = c("copper","others"), labels = c("Copper","Pulp wood, Fruit, Salmon & Others"))
stackedchart.data <- ddply(stackedchart.data, .(year), transform, pos = cumsum(percentage) - (0.5 * percentage))
stackedchart.data <- ddply(stackedchart.data, .(year), transform, pos2 = cumsum(export) - (0.5 * export))

p10 <- ggplot() + geom_bar(aes(y = percentage, x = year, fill = product), data = stackedchart.data, stat="identity")
p10 <- p10 + geom_text(data=stackedchart.data, aes(x = year, y = pos, label = paste0(percentage,"%")))
p10
```

```{r, cache=TRUE}
p10 <- p10 + theme(legend.position="bottom", legend.direction="horizontal", legend.title = element_blank())
p10
```

```{r, cache=TRUE}
library(scales)
p10 <- p10 + scale_x_continuous(breaks=seq(2006,2014,1)) + scale_y_continuous(labels = dollar_format(suffix = "%", prefix = ""))
p10
```

```{r, cache=TRUE}
p10 <- p10 + labs(x="Year", y="Percentage") + ggtitle("Composition of Exports to China (%)") 
p10
```

```{r, cache=TRUE}
fill <- c("#56B4E9", "#E69F00")
p10 <- p10 + scale_fill_manual(values=fill)
p10
```

```{r, cache=TRUE}
p10 <- ggplot() + 
  geom_bar(aes(y = percentage, x = year, fill = product), data = stackedchart.data, stat="identity") + 
  geom_text(data=stackedchart.data, aes(x = year, y = pos, label = paste0(percentage,"%")), colour="black", family="AdobeHeitiStd-Regular", size = 5) + 
  theme(legend.position="bottom", legend.direction="horizontal", legend.title = element_blank()) + 
  scale_x_continuous(breaks=seq(2006,2014,1)) + 
  scale_y_continuous(labels = dollar_format(suffix = "%", prefix = "")) + 
  labs(x="Year", y="Percentage") + 
  ggtitle("Composition of Exports to China (%)") + 
  scale_fill_manual(values=fill) + 
  theme(axis.line = element_line(size=1.5)) + 
  theme(panel.background = element_rect(fill="white"), panel.grid = element_line(colour="white")) + 
  theme(plot.title=element_text(family="AdobeHeitiStd-Regular"), text=element_text(family="AdobeHeitiStd-Regular"), axis.text.x=element_text(colour="black"), axis.text.y=element_text(colour="black")) 
p10
```

```{r, cache=TRUE}
p10 <- ggplot() + 
  geom_bar(aes(y = percentage, x = year, fill = product), data = stackedchart.data, stat="identity") + 
  geom_text(data=stackedchart.data, aes(x = year, y = pos, label = paste0(percentage,"%")), colour="black", family="xkcd-Regular", size = 5) + 
  theme(legend.position="bottom", legend.direction="horizontal", legend.title = element_blank()) + 
  scale_x_continuous(breaks=seq(2006,2014,1)) + 
  scale_y_continuous(labels = dollar_format(suffix = "%", prefix = "")) + 
  labs(x="Year", y="Percentage") + 
  ggtitle("Composition of Exports to China (%)") + 
  scale_fill_manual(values=fill) + 
  theme(axis.line = element_line(size=1.5)) + 
  theme(panel.background = element_rect(fill="white"), panel.grid = element_line(colour="white")) + 
  theme(plot.title=element_text(family="xkcd-Regular"), text=element_text(family="xkcd-Regular"), axis.text.x=element_text(colour="black"), axis.text.y=element_text(colour="black")) 
p10
```






